version: "3.8"
   
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbPass
      MYSQL_DATABASE: mysqlDatabase
      MYSQL_ROOT: Mysql_root
      MYSQL_ROOT_PASSWORD: rootPass
    restart:
      unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql:ro
    ports:
      - "3306:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
